name: ci

on:
  - push
  - pull_request

#language: cpp

jobs:
  test:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false

    env:
      CI: true
    steps:
    - uses: actions/checkout@v2
    - name: Setup apt sources
      run: |
        echo "deb http://us.archive.ubuntu.com/ubuntu/ xenial main" | sudo tee -a /etc/apt/sources.list
        echo "deb http://us.archive.ubuntu.com/ubuntu/ xenial universe" | sudo tee -a /etc/apt/sources.list
        sudo apt-get update -qq
        sudo apt-get install gcc extra-cmake-modules qtbase5-dev libkf5coreaddons-dev libkdecorations2-dev -y
    - name: Build source
      run: |
        cmake . -DCMAKE_INSTALL_PREFIX=build && make install
    - name: Compress for deploy
      run: |
        tar -zcf kdecoration2-kde2.tar.gz build/lib/x86_64-linux-gnu

#deploy:
  #provider: releases
  #api_key:
    #secure: ...
  #file: kdecoration2-kde2.tar.gz
  #skip_cleanup: true
  #on:
    #tags: true
